---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart flink-jobmanager
  systemd:
    name: flink-jobmanager
    state: restarted
  when: "'flink_jobmanager' in group_names"

- name: restart flink-taskmanager
  systemd:
    name: flink-taskmanager
    state: restarted
  when: "'flink_taskmanager' in group_names"
