---
# =============================================================================
# cp_mongodb defaults
# =============================================================================
cp_mongodb_source_connectors: []
cp_mongodb_sink_connectors: []

cp_connect_validate_health: true
cp_connect_health_retries: 12
cp_connect_health_delay: 10
