---
- name: Delegate Redis deploy to cp_connect
  ansible.builtin.include_role:
    name: cp_connect
    tasks_from: deploy.yml
  vars:
    cp_connectors: "{{ cp_redis_sink_connectors | default([]) }}"
  when: (cp_redis_sink_connectors | default([])) | length > 0
