# CPTopic definition for fraud detection alert signal topic
apiVersion: platform.confluent.io/v1beta1
kind: CPTopic
metadata:
  name: fraud.detection.v1.alert-signal
  labels:
    fsi.domain: fraud
    fsi.application: detection
    fsi.version: v1
    fsi.entity: alert-signal
    fsi.sla-tier: critical
    fsi.owner: fraud-team@company.com
    fsi.data-classification: internal
spec:
  partitionCount: 12
  configs:
    retention.ms: 604800000
    min.insync.replicas: 2
    cleanup.policy: delete
