---
- name: Delegate CockroachDB check mode to cp_connect
  ansible.builtin.include_role:
    name: cp_connect
    tasks_from: check.yml
  vars:
    cp_connectors: "{{ cp_cockroachdb_sink_connectors | default([]) }}"
  when: (cp_cockroachdb_sink_connectors | default([])) | length > 0
