---
- name: MM2 DR Failback
  hosts: kafka_connect[0]
  gather_facts: false
  vars:
    cp_dr_mm2_operation: failback
  tasks:
    - name: Execute MM2 DR failback
      ansible.builtin.include_role:
        name: cp_dr_mm2
