---
# =============================================================================
# cp_redis defaults
# =============================================================================
cp_redis_sink_connectors: []

cp_connect_validate_health: true
cp_connect_health_retries: 12
cp_connect_health_delay: 10
