---
# =============================================================================
# Postgres JDBC Sink Connector -- ADR-012 (Kafka -> Postgres)
# =============================================================================
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: database-postgres-sink-compliance-reporting
  namespace: confluent
  labels:
    app.kubernetes.io/part-of: fsi-kafka-platform
    fsi.io/connector-type: postgres-sink
    fsi.io/sla-tier: standard
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  taskMax: 3
  connectClusterRef:
    name: connect-databases
  configs:
    connection.url: "jdbc:postgresql://<PLACEHOLDER_POSTGRES_REPORTING_HOST>:5432/reporting?sslmode=verify-full&sslrootcert=/mnt/sslcerts/postgres-ca.crt"
    connection.user: "${file:/mnt/secrets/database/postgres:username}"
    connection.password: "${file:/mnt/secrets/database/postgres:password}"

    topics: "compliance.screening.v1.match-result"

    table.name.format: "compliance_screening_result"
    insert.mode: "upsert"
    pk.mode: "record_value"
    pk.fields: "match_id"
    auto.create: "false"
    auto.evolve: "false"
    batch.size: "3000"

    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "https://schemaregistry.confluent.svc.cluster.local:8081"
    value.converter.basic.auth.credentials.source: "USER_INFO"
    value.converter.basic.auth.user.info: "${file:/mnt/secrets/database/sr:user_info}"

    errors.tolerance: "all"
    errors.deadletterqueue.topic.name: "database.dlq.postgres-sink-compliance-reporting"
    errors.deadletterqueue.context.headers.enable: "true"
    errors.log.enable: "true"
    errors.log.include.messages: "false"
