apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
spec:
  tls:
    secretRef: connect-tls
    fips:
      enabled: true
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - s390x
  configOverrides:
    server:
      - ssl.enabled.protocols=TLSv1.3,TLSv1.2
      - ssl.cipher.suites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
